language: android
android:
  components:
   - tools
   - platform-tools
   - tools

    # The BuildTools version
    - build-tools-26.0.2

    # The SDK version
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # system image
    - sys-img-armeabi-v7a-android-22